const fractalOwlImages = [
  {
    src: '../assets/images/website-gallery/owl_03-04.png',
    alt: 'Owl Wall Art Fractal Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 1,
    category: 'Fractal-Owl',
    title: 'Cosmic Companion',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/owl_00-02.png',
    alt: 'Owl Wall Art Fractal Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 2,
    category: 'Fractal-Owl',
    title: 'Fractal Feathered Friend',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/owl_01-02.png',
    alt: 'Owl Wall Art Fractal Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 3,
    category: 'Fractal-Owl',
    title: 'Artistic Avian',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/owl_04-05.png',
    alt: 'Owl Wall Art Fractal Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 4,
    category: 'Fractal-Owl',
    title: 'Nebula Night Owl',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/owl_02-00.png',
    alt: 'Owl Wall Art Fractal Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 5,
    category: 'Fractal-Owl',
    title: 'Fractured Fascination',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
];

const splashSilhouetteImages = [
  {
    src: '../assets/images/website-gallery/splash_silhouette-07_CLEAN.png',
    alt: 'Watercolor Wall Art Splash Silhouette Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 6,
    category: 'Splash-Silhouette',
    title: 'Watercolor Waltz',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/splash_silhouette-20_CLEAN.png',
    alt: 'Watercolor Wall Art Splash Silhouette Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 7,
    category: 'Splash-Silhouette',
    title: 'Brushstroke Ballet',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/splash_silhouette-25_CLEAN.png',
    alt: 'Watercolor Wall Art Splash Silhouette Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 8,
    category: 'Splash-Silhouette',
    title: 'Effervescent Expression',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/splash_silhouette-26_00_CLEAN.png',
    alt: 'Watercolor Wall Art Splash Silhouette Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 9,
    category: 'Splash-Silhouette',
    title: 'Painted Passion',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
];

const bioluminescentGoddessImages = [
  {
    src: '../assets/images/website-gallery/bio-goddess_00.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 10,
    category: 'Bioluminescent-Goddess',
    title: 'Fluorescent Fairy',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_01.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 11,
    category: 'Bioluminescent-Goddess',
    title: 'Gossamer Glamou',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_02.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 12,
    category: 'Bioluminescent-Goddess',
    title: 'Nebula Nettles',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_03.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 13,
    category: 'Bioluminescent-Goddess',
    title: 'Luminescent Lady 1',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_04.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 14,
    category: 'Bioluminescent-Goddess',
    title: 'Luminescent Lady 2',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_05.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 15,
    category: 'Bioluminescent-Goddess',
    title: 'Luminescent Lady 3',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_06.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 16,
    category: 'Bioluminescent-Goddess',
    title: 'Luminescent Lady 4',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_07.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 17,
    category: 'Bioluminescent-Goddess',
    title: 'Shimmering Sprite 1',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_08.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 18,
    category: 'Bioluminescent-Goddess',
    title: 'Shimmering Sprite 2',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/bio-goddess_09.png',
    alt: 'Otherworldly Wall Art Bioluminescence Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 19,
    category: 'Bioluminescent-Goddess',
    title: 'Shimmering Sprite 3',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
];

const copperGoddessImages = [
  {
    src: '../assets/images/website-gallery/copper-goddess_00.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 20,
    category: 'Copper-Goddess',
    title: 'Copper Crowned Deity',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/copper-goddess_01.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 21,
    category: 'Copper-Goddess',
    title: 'Wire Woven Warrior',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/copper-goddess_02.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 22,
    category: 'Copper-Goddess',
    title: 'Dark Divine',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/copper-goddess_03.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 23,
    category: 'Copper-Goddess',
    title: 'Electric Empress',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/copper-goddess_04.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 24,
    category: 'Copper-Goddess',
    title: 'Brazen Beauty',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
  {
    src: '../assets/images/website-gallery/copper-goddess_05.png',
    alt: 'Wallpaper Wall Art Copper Goddess Digital Print',
    href: 'https://www.etsy.com/shop/TranscendentTreez',
    id: 25,
    category: 'Copper-Goddess',
    title: 'Soldered Sovereignty',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
  },
];

const imagesData = (() => {
  return {
    fractalOwlImages,
    splashSilhouetteImages,
    bioluminescentGoddessImages,
    copperGoddessImages,
  };
})();

export default imagesData;